# airports:
#   cache:
#     ttl: 60
#     heap-size: 100

---
spring:
  config:
    activate:
      on-profile: default
eureka:
  instance:
    # enable to register multiple app instances with a random server port
    instance-id: ${spring.application.name}:${random.uuid}

airport: KMAH

fbo:
  fuel: 100LL

---
spring:
  config:
    activate:
      on-profile: local
  zipkin:
    baseUrl: http://tracing-service:9411
server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
