server:
  port: 9411

---
spring:
  profiles: default
eureka:
  instance:
    # enable to register multiple app instances with a random server port
    instance-id: ${spring.application.name}:${random.uuid}

---
spring:
  config:
    activate:
      on-profile: local
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
